language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
  - sudo apt-get install -y libgoogle-perftools-dev libsdl2-dev
